In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle


In [3]:
#reading the file
data=pd.read_csv('CampusPlace.csv')
data

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p workex  \
0        1      M  87.00   Others  91.00   Others  Commerce     88.00     No   
1        2      M  79.33  Central  78.33   Others   Science     77.48    Yes   
2        3      M  85.00  Central  79.00  Central      Arts     90.00     No   
3        4      M  56.00  Central  52.00  Central   Science     52.00     No   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30     No   
..     ...    ...    ...      ...    ...      ...       ...       ...    ...   
210    211      M  80.60   Others  82.00   Others   Science     87.00     No   
211    212      M  80.00   Others  87.00   Others   Science     82.00     No   
212    213      M  67.00   Others  90.00   Others   Science     83.00    Yes   
213    214      F  74.00   Others  89.00   Others   Science     88.00     No   
214    215      M  62.00  Central  58.00   Others   Science     53.00     No   

     etest_p specialisation      status    salary  
0       87.0             CS      Placed  270000.0  
1       86.5             IT      Placed  200000.0  
2       94.0             IT      Placed  250000.0  
3       66.0             CS  Not Placed       NaN  
4       96.8             IT      Placed  425000.0  
..       ...            ...         ...       ...  
210     91.0             IT      Placed  400000.0  
211     84.0             IT      Placed  275000.0  
212     89.0             IT      Placed  295000.0  
213     80.0             CS      Placed  204000.0  
214     74.0             CS  Not Placed       NaN  

[215 rows x 13 columns]

In [4]:
#droping the serial no and salary col
data=data.drop('sl_no',axis=1)
data=data.drop('salary',axis=1)
data.head()


gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p workex  etest_p  \
0      M  87.00   Others  91.00   Others  Commerce     88.00     No     87.0   
1      M  79.33  Central  78.33   Others   Science     77.48    Yes     86.5   
2      M  85.00  Central  79.00  Central      Arts     90.00     No     94.0   
3      M  56.00  Central  52.00  Central   Science     52.00     No     66.0   
4      M  85.80  Central  73.60  Central  Commerce     73.30     No     96.8   

  specialisation      status  
0             CS      Placed  
1             IT      Placed  
2             IT      Placed  
3             CS  Not Placed  
4             IT      Placed

In [5]:
data.shape

(215, 11)

In [6]:
#catgorising col for further labelling
data["gender"]=data["gender"].astype('category')
data["ssc_b"]=data["ssc_b"].astype('category')
data["hsc_b"]=data["hsc_b"].astype('category')
data["workex"]=data["workex"].astype('category')
data["specialisation"]=data["specialisation"].astype('category')
data["status"]=data["status"].astype('category')
data["hsc_s"]=data["hsc_s"].astype('category')
data.dtypes


gender            category
ssc_p              float64
ssc_b             category
hsc_p              float64
hsc_b             category
hsc_s             category
degree_p           float64
workex            category
etest_p            float64
specialisation    category
status            category
dtype: object

In [7]:
#labelling the col
data["gender"]=data["gender"].cat.codes
data["ssc_b"]=data["ssc_b"].cat.codes
data["hsc_b"]=data["hsc_b"].cat.codes
data["workex"]=data["workex"].cat.codes
data["specialisation"]=data["specialisation"].cat.codes
data["status"]=data["status"].cat.codes
data["hsc_s"]=data["hsc_s"].cat.codes
data

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  workex  etest_p  \
0         1  87.00      1  91.00      1      1     88.00       0     87.0   
1         1  79.33      0  78.33      1      2     77.48       1     86.5   
2         1  85.00      0  79.00      0      0     90.00       0     94.0   
3         1  56.00      0  52.00      0      2     52.00       0     66.0   
4         1  85.80      0  73.60      0      1     73.30       0     96.8   
..      ...    ...    ...    ...    ...    ...       ...     ...      ...   
210       1  80.60      1  82.00      1      2     87.00       0     91.0   
211       1  80.00      1  87.00      1      2     82.00       0     84.0   
212       1  67.00      1  90.00      1      2     83.00       1     89.0   
213       0  74.00      1  89.00      1      2     88.00       0     80.0   
214       1  62.00      0  58.00      1      2     53.00       0     74.0   

     specialisation  status  
0                 0       1  
1                 1       1  
2                 1       1  
3                 0       0  
4                 1       1  
..              ...     ...  
210               1       1  
211               1       1  
212               1       1  
213               0       1  
214               0       0  

[215 rows x 11 columns]

In [10]:
#selecting the features and labels
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values
print(Y.shape)
print(Y)



(215,)
[1 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0
 1 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1
 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1
 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0
 1 0 1 0 0 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0]


In [11]:
print(X.shape)
print(X)

(215, 10)
[[ 1.   87.    1.   ...  0.   87.    0.  ]
 [ 1.   79.33  0.   ...  1.   86.5   1.  ]
 [ 1.   85.    0.   ...  0.   94.    1.  ]
 ...
 [ 1.   67.    1.   ...  1.   89.    1.  ]
 [ 0.   74.    1.   ...  0.   80.    0.  ]
 [ 1.   62.    0.   ...  0.   74.    0.  ]]


In [14]:
#dividing the data into train and split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
print(X_train)
print(X_train.shape)

[[ 1.  87.   1.  ...  0.  95.   0. ]
 [ 0.  67.   0.  ...  0.  70.   0. ]
 [ 0.  80.   0.  ...  1.  80.   0. ]
 ...
 [ 1.  66.   0.  ...  0.  60.   0. ]
 [ 1.  87.   0.  ...  0.  93.4  1. ]
 [ 1.  81.   1.  ...  1.  88.   1. ]]
(172, 10)


In [15]:
print(X_test)
print(X_test.shape)

[[ 1.   87.    0.   85.    1.    2.   92.    0.   87.    1.  ]
 [ 0.   56.28  1.   62.83  1.    2.   59.79  0.   60.    0.  ]
 [ 0.   82.    1.   82.    1.    2.   89.    1.   87.    0.  ]
 [ 1.   86.    0.   84.    0.    2.   80.    0.   84.27  1.  ]
 [ 1.   89.    0.   95.    0.    2.   90.    1.   95.    1.  ]
 [ 1.   86.    0.   85.    1.    2.   89.    1.   86.    1.  ]
 [ 1.   80.    1.   86.    1.    2.   85.    0.   82.    1.  ]
 [ 0.   85.    1.   90.    1.    2.   82.    0.   92.    1.  ]
 [ 1.   80.    0.   84.    0.    2.   86.    0.   81.    0.  ]
 [ 1.   82.    1.   86.    1.    2.   80.    1.   83.    0.  ]
 [ 0.   81.    1.   89.    0.    2.   84.    0.   98.    1.  ]
 [ 1.   90.    1.   84.    1.    0.   87.    1.   82.    1.  ]
 [ 0.   90.    0.   87.    0.    2.   89.    0.   88.    1.  ]
 [ 1.   94.    0.   83.    1.    2.   85.    0.   85.    0.  ]
 [ 1.   83.    1.   87.    1.    2.   84.    0.   85.    1.  ]
 [ 1.   90.    1.   80.    1.    1.   87.    0.   85.  

In [16]:
print(Y_test)
print(Y_test.shape)


[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 0
 1 1 0 1 1 1]
(43,)


In [17]:
print(Y_train)
print(Y_train.shape)

[1 0 1 0 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 1 0
 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 0
 1 1 0 1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 0
 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1]
(172,)


In [18]:
#creating a classifier using sklearn
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train,Y_train)
#printing the acc
clf.score(X_test,Y_test)


D:\anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


1.0

In [19]:
#predicting for random value
clf.predict([[1,77,0,95,0,2,80,0,0,1]])

array([1], dtype=int8)

In [20]:
clf.predict([[1,57,0,55,0,2,58,0,0,1]])

array([0], dtype=int8)

In [21]:

#creating a Y_pred for test data
Y_pred=clf.predict(X_test)
Y_pred

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1],
      dtype=int8)

In [22]:
#model generation
pickle.dump(clf, open('modelCampus.pkl','wb'))
#evalution of the classifier
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[ 9  0]
 [ 0 34]]


1.0