In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle


In [2]:
#reading the file
data=pd.read_csv('Scholarship.csv')
data

Sl No. Student Name               Scholarship Name     caste  \
0         1        Priya                    Post-Metric  Catholic   
1         2        tanya  Karnataka Minority Schlorship    Muslim   
2         3       ramesh       Children of Beedi Worker       NaN   
3         4       suresh          Children of Mica/Iron       NaN   
4         5         jaya   Differently Abled Schlorship       NaN   
..      ...          ...                            ...       ...   
176      57         rhea                 No Scholarship       NaN   
177      58       ashota                 No Scholarship       NaN   
178      59        ethan                 No Scholarship    Muslim   
179      60       renola                 No Scholarship       NaN   
180      61        athan                 No Scholarship    Muslim   

     marks of previous year gender  Annual Income  
0                        68      M          20000  
1                        70      F          20000  
2                        98      M          15000  
3                        78      M          12000  
4                        56      F          35000  
..                      ...    ...            ...  
176                      34      F           8000  
177                      20      F          15000  
178                      36      M          20000  
179                      25      F           8000  
180                      37      M          20000  

[181 rows x 7 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Sl No.                  181 non-null    int64 
 1   Student Name            181 non-null    object
 2   Scholarship Name        181 non-null    object
 3   caste                   52 non-null     object
 4   marks of previous year  181 non-null    int64 
 5   gender                  181 non-null    object
 6   Annual Income           181 non-null    int64 
dtypes: int64(3), object(4)
memory usage: 10.0+ KB


In [4]:
data.isnull().sum()

Sl No.                      0
Student Name                0
Scholarship Name            0
caste                     129
marks of previous year      0
gender                      0
Annual Income               0
dtype: int64

In [5]:
data['caste'].fillna('Other',inplace=True)


In [6]:
data

Sl No. Student Name               Scholarship Name     caste  \
0         1        Priya                    Post-Metric  Catholic   
1         2        tanya  Karnataka Minority Schlorship    Muslim   
2         3       ramesh       Children of Beedi Worker     Other   
3         4       suresh          Children of Mica/Iron     Other   
4         5         jaya   Differently Abled Schlorship     Other   
..      ...          ...                            ...       ...   
176      57         rhea                 No Scholarship     Other   
177      58       ashota                 No Scholarship     Other   
178      59        ethan                 No Scholarship    Muslim   
179      60       renola                 No Scholarship     Other   
180      61        athan                 No Scholarship    Muslim   

     marks of previous year gender  Annual Income  
0                        68      M          20000  
1                        70      F          20000  
2                        98      M          15000  
3                        78      M          12000  
4                        56      F          35000  
..                      ...    ...            ...  
176                      34      F           8000  
177                      20      F          15000  
178                      36      M          20000  
179                      25      F           8000  
180                      37      M          20000  

[181 rows x 7 columns]

In [7]:
data['Scholarship Name'].nunique()

11

In [8]:
data['Scholarship Name'].unique()

array(['Post-Metric', 'Karnataka Minority Schlorship',
       'Children of Beedi Worker', 'Children of Mica/Iron',
       'Differently Abled Schlorship',
       'Labour welfare commission schlorship', 'LIC schlorship',
       'NTPC Scholarship Scheme', 'VIT University Ignite Scholarships',
       'Indian Oil Corporation Scholarships', 'No Scholarship'],
      dtype=object)

In [9]:
scholarship_dict={'No Scholarship':0,'Post-Metric':1, 'Karnataka Minority Schlorship':2,
       'Children of Beedi Worker':3, 'Children of Mica/Iron':4,
       'Differently Abled Schlorship':5,
       'Labour welfare commission schlorship':6, 'LIC schlorship':7,
       'NTPC Scholarship Scheme':8, 'VIT University Ignite Scholarships':9,
       'Indian Oil Corporation Scholarships':10}
data['Scholarship Name']=data['Scholarship Name'].map(scholarship_dict)

In [10]:
data

Sl No. Student Name  Scholarship Name     caste  marks of previous year  \
0         1        Priya                 1  Catholic                      68   
1         2        tanya                 2    Muslim                      70   
2         3       ramesh                 3     Other                      98   
3         4       suresh                 4     Other                      78   
4         5         jaya                 5     Other                      56   
..      ...          ...               ...       ...                     ...   
176      57         rhea                 0     Other                      34   
177      58       ashota                 0     Other                      20   
178      59        ethan                 0    Muslim                      36   
179      60       renola                 0     Other                      25   
180      61        athan                 0    Muslim                      37   

    gender  Annual Income  
0        M          20000  
1        F          20000  
2        M          15000  
3        M          12000  
4        F          35000  
..     ...            ...  
176      F           8000  
177      F          15000  
178      M          20000  
179      F           8000  
180      M          20000  

[181 rows x 7 columns]

In [11]:
#droping the serial no and salary col
data=data.drop('Sl No.',axis=1)
data=data.drop('Student Name',axis=1)
data.head()


Scholarship Name     caste  marks of previous year gender  Annual Income
0                 1  Catholic                      68      M          20000
1                 2    Muslim                      70      F          20000
2                 3     Other                      98      M          15000
3                 4     Other                      78      M          12000
4                 5     Other                      56      F          35000

In [12]:
data['gender']=data['gender'].map({'M':0,'F':1})
data

Scholarship Name     caste  marks of previous year  gender  Annual Income
0                   1  Catholic                      68       0          20000
1                   2    Muslim                      70       1          20000
2                   3     Other                      98       0          15000
3                   4     Other                      78       0          12000
4                   5     Other                      56       1          35000
..                ...       ...                     ...     ...            ...
176                 0     Other                      34       1           8000
177                 0     Other                      20       1          15000
178                 0    Muslim                      36       0          20000
179                 0     Other                      25       1           8000
180                 0    Muslim                      37       0          20000

[181 rows x 5 columns]

In [13]:
data['caste']=data['caste'].map({'Catholic':1,'Muslim':2,'Other':3})
data

Scholarship Name  caste  marks of previous year  gender  Annual Income
0                   1      1                      68       0          20000
1                   2      2                      70       1          20000
2                   3      3                      98       0          15000
3                   4      3                      78       0          12000
4                   5      3                      56       1          35000
..                ...    ...                     ...     ...            ...
176                 0      3                      34       1           8000
177                 0      3                      20       1          15000
178                 0      2                      36       0          20000
179                 0      3                      25       1           8000
180                 0      2                      37       0          20000

[181 rows x 5 columns]

In [14]:
#selecting the features and labels
X=data.iloc[:,1:].values
Y=data.iloc[:,0].values
print(X.shape)
print(X)
print(Y.shape)
print(Y)

(181, 4)
[[      1      68       0   20000]
 [      2      70       1   20000]
 [      3      98       0   15000]
 [      3      78       0   12000]
 [      3      56       1   35000]
 [      3      76       0   10000]
 [      3      34       1    5000]
 [      3      76       1    9000]
 [      3      98       0    8000]
 [      3      67       1    5000]
 [      1      56       0   20000]
 [      1      87       0   20000]
 [      3      76       0   15000]
 [      3      98       1   12000]
 [      3      89       0   15000]
 [      3      78       1   12000]
 [      3      65       0    5000]
 [      3      56       1    9000]
 [      3      77       1    8000]
 [      3      98       0   15000]
 [      3      67       1   12000]
 [      3      56       0    5000]
 [      3      76       1    5000]
 [      3      87       1    9000]
 [      3      56       0    8000]
 [      3      66       0   15000]
 [      3      88       1   12000]
 [      3      67       1   12000]
 [      3  

In [15]:
#dividing the data into train and split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)
print(X_train)
print(X_train.shape)

[[      3      76       0   15000]
 [      3      56       0  310000]
 [      3      88       1  260000]
 [      3      29       1   12000]
 [      3      56       0  260000]
 [      2      78       0   20000]
 [      3      99       0  200000]
 [      3      78       0   12000]
 [      1      35       1   20000]
 [      3      99       0   35000]
 [      3      56       0 3300000]
 [      2      65       0   20000]
 [      3      77       1    8000]
 [      3      78       1    8000]
 [      1      34       0   20000]
 [      3      67       1  230000]
 [      3      34       0    8000]
 [      3      76       0   15000]
 [      2      65       0  230000]
 [      3      76       0  330000]
 [      3      87       0   35000]
 [      3      98       1  270000]
 [      3      36       1    8000]
 [      3      67       0  410000]
 [      3      29       0   15000]
 [      3      56       1    9000]
 [      3      33       1   10000]
 [      3      36       1   35000]
 [      2      78   

In [16]:
print(Y_train)
print(Y_train.shape)

[ 3  0  0  0  0  1  0  4  0  5  0  1  9  9  0  0  0  3  0  0  5  0  0  0
  0  8  0  0  0  4  0  0  1  0  1  0  0  0  0  0  0  0  0  7  0  3  0  0
  7  0  1  0  0  0  8  0  0  0  1  0  0  0  0  0  0  0  0  1  4  3  0  3
  0  0  0  4  0  8  0  0 10  0  0  0  0  0  0  0  0  0  0  0  4  2  0  0
  0  1  4  0  4  9  4  0  1  0  0  7  0  0  0  9  1  0  2  3  7  0  0  8
  0  0  0  0  0  9  0  0  0  0  0  0  4  3  0  0  0  0  0  0  0  0  0  1]
(144,)


In [17]:
print(X_test.shape)
print(X_test)

(37, 4)
[[      3      66       1  270000]
 [      3      44       1  300000]
 [      2      56       1  220000]
 [      1      29       1   20000]
 [      1      76       1   20000]
 [      3      98       1    5000]
 [      3      98       0  250000]
 [      3      98       0   15000]
 [      3      31       0   10000]
 [      3      31       0    5000]
 [      1      65       0  300000]
 [      3      76       0  230000]
 [      1      87       0   20000]
 [      3      87       1  250000]
 [      3      56       1   35000]
 [      3      87       1  310000]
 [      3      89       0   15000]
 [      3      34       0   15000]
 [      3      98       1   10000]
 [      3      98       1  220000]
 [      3      36       1   12000]
 [      1      65       1   20000]
 [      3      87       1   20000]
 [      3      34       1    8000]
 [      1      87       0   20000]
 [      2      67       1   20000]
 [      3      87       1   12000]
 [      3      76       0  230000]
 [      2   

In [18]:
print(Y_test.shape)
print(Y_test)

(37,)
[0 0 0 0 1 7 0 3 0 0 0 0 2 0 5 0 3 0 6 0 0 1 2 0 1 1 4 0 0 9 7 0 9 0 6 0 0]


In [19]:
#creating a classifier using sklearn
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


lr =  LogisticRegression()
lr.fit(X_train, Y_train)
Y_pred=lr.predict(X_test)

df=pd.DataFrame({'Actual':Y_test,"Predicted":Y_pred})

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

print(df)


0.5945945945945946
[[20  0  0  0  1  0  0  0  0]
 [ 3  1  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  2  0  0  0  0]]
    Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        1          0
5        7          9
6        0          0
7        3          4
8        0          0
9        0          4
10       0          0
11       0          0
12       2          1
13       0          0
14       5          0
15       0          0
16       3          4
17       0          0
18       6          9
19       0          0
20       0          0
21       1          0
22       2          1
23       0          0
24       1          1
25       1          0
26       4          4
27       0          0
28       0          0
29       9          4
30       7          9
31    

D:\anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
#creating a classifier using sklearn
from sklearn.naive_bayes import GaussianNB

nb =  GaussianNB()
nb.fit(X_train, Y_train)
Y_pred=nb.predict(X_test)

df=pd.DataFrame({'Actual':Y_test,"Predicted":Y_pred})

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

print(df)

0.7027027027027027
[[14  2  0  1  2  0  0  1  1]
 [ 0  4  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0]
 [ 2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  2]]
    Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          1
4        1          1
5        7          7
6        0          0
7        3          3
8        0          0
9        0          7
10       0          0
11       0          0
12       2          1
13       0          0
14       5          5
15       0          0
16       3          3
17       0          3
18       6          0
19       0          0
20       0          4
21       1          1
22       2          1
23       0          9
24       1          1
25       1          1
26       4          4
27       0          0
28       0          0
29       9          9
30       7          7
31    

In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, Y_train)
Y_pred=knn.predict(X_test)

df=pd.DataFrame({'Actual':Y_test,"Predicted":Y_pred})

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

print(df)

0.8378378378378378
[[21  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  1]]
    Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        1          1
5        7          7
6        0          0
7        3          3
8        0          0
9        0          0
10       0          0
11       0          0
12       2          1
13       0          0
14       5          0
15       0          0
16       3          3
17       0          0
18       6          8
19       0          0
20       0          0
21       1          1
22       2          1
23       0          0
24       1          1
25       1          1
26       4          4
27       0          0
28       0  

In [22]:
#model generation
import pickle
pickle.dump(knn, open('scholar_model.pkl','wb'))

In [23]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(max_depth=3,random_state=0, max_features = None,  min_samples_leaf = 2)
dtree.fit(X_train, Y_train)
Y_pred=dtree.predict(X_test)

df=pd.DataFrame({'Actual':Y_test,"Predicted":Y_pred})

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

print(df)



0.7027027027027027
[[21  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0]
 [ 0  1  0  0  1  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0]]
    Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        1          1
5        7          4
6        0          0
7        3          4
8        0          0
9        0          0
10       0          0
11       0          0
12       2          1
13       0          0
14       5          4
15       0          0
16       3          4
17       0          0
18       6          4
19       0          0
20       0          0
21       1          1
22       2          4
23       0          0
24       1          1
25       1          1
26       4          4
27       0          0
28       0          0
29       9          4
30       7          4
31    

In [24]:
from sklearn.svm import SVC

svm =  SVC(gamma='auto')

svm.fit(X_train, Y_train)
Y_pred=svm.predict(X_test)

df=pd.DataFrame({'Actual':Y_test,"Predicted":Y_pred})

print(accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))

print(df)


0.6756756756756757
[[21  0  0  0  0  0  0  0  0]
 [ 1  3  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0]]
    Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        1          0
5        7          0
6        0          0
7        3          3
8        0          0
9        0          0
10       0          0
11       0          0
12       2          1
13       0          0
14       5          0
15       0          0
16       3          0
17       0          0
18       6          0
19       0          0
20       0          0
21       1          1
22       2          1
23       0          0
24       1          1
25       1          1
26       4          0
27       0          0
28       0          0
29       9          0
30       7          0
31    

In [29]:
knn.predict([[1,88,1,500000]])

array([0], dtype=int64)